### ISSUE TITLE
[EPIC] - Dashboard for Business Owner

### ISSUE THREAD

**Issue by davidindub** [davidindub/coffeecrew#41]
## Description
There should be a dashboard with CRUD functionality for the business owner

## Initiative / goal
The goal is that the project can be handed over to a business owner and all current functionality can be tweaked without the need to edit code.
A frontend for the business owner where site settings can be changed without the use of the Django Admin panel.

### Hypothesis
The business owner should be able to add, hide, and remove products from sale, as well as edit settings such as postage costs.

When future features are added, they need to be included in this dashboard too.

- [x] Add new products
- [x] Edit products
- [x] Hide products
- [x] Remove products 
- [x] Add categories
- [x] Edit categories
- [x] Hide categories
- [x] Remove categories
- [x] Add departments
- [x] Edit departments
- [x] Hide departments
- [x] Remove departments

- [x] See all orders
- [x] See undispatched orders
- [x] Print orders
- [x] Mark orders as dispatched

- [x] Edit postage costs
